version: '3.4'
services:
  redis:
    image: redis
    container_name: ospredis
    expose:
      - 6379
  app:
    build: .
    restart: always
    ports:
      - '1935:1935'
      - '8585:80'
      - '8553:443'
    environment:
      - REDIS_HOST=ospredis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
#       - DB_URL="sqlite:///db/database.db"
#       - FLASK_SECRET="Super-Sekrit"
#       - FLASK_SALT="SALT123"
#       - OSP_ALLOWREGISTRATION=True
#       - OSP_REQUIREVERIFICATION=True
#       - TZ="ETC/UTC"
#    volumes:
#      - "./data/www:/var/www"
#      - "./data/osp/db/database.db:/opt/osp/db/database.db"
#      - "./data/nginx/conf:/usr/local/nginx/conf"
#    networks:
#      - traefik
#    labels:
#      # Uncomment traefik labels for reverse proxy front end.
#      - "traefik.port=443"
#      - "traefik.frontend.rule=Host:osp.example.com"
#      - "traefik.backend=osp"
#      - "traefik.docker.network=traefik"
#      - "traefik.expose=true"
#networks:
#  traefik:
